<?php
/**
 * Define the demo import files (local files).
 *
 * You have to use the same filter as in above example,
 * but with a slightly different array keys: local_*.
 * The values have to be absolute paths (not URLs) to your import files.
 * To use local import files, that reside in your theme folder,
 * please use the below code.
 * Note: make sure your import files are readable!
 */
function woostify_sites_local_import_files() {
	return array(
		array(
			'id'                           => 0,
			'import_file_name'             => 'Fashion',
			'local_import_file'            => WOOSTIFY_SITES_DIR . 'demos/demo-1/data.xml',
			'local_import_widget_file'     => WOOSTIFY_SITES_DIR . 'demos/demo-1/widgets.wie',
			'local_import_customizer_file' => WOOSTIFY_SITES_DIR . 'demos/demo-1/customizer.dat',
			'import_preview_image_url'     => WOOSTIFY_SITES_URI . 'demos/demo-1/demo-11.jpg',
			'import_notice'                => __( 'After you import this demo, you will have to setup the slider separately.', 'woostify' ),
			'preview_url'                  => 'https://freedemo.woostify.com/fashion1/',
			'homepage'                     => 'Fashion',
			'blog_page'                    => 'Blog',
			'primary_menu'                 => 'Header Primary',
			'footer_menu'                  => 'Footer',
			'type'                         => 'free',
			'page_builder'                 => 'elementor',
		),
		array(
			'id'                           => 1,
			'import_file_name'             => 'Yoga',
			'local_import_file'            => WOOSTIFY_SITES_DIR . 'demos/demo-2/demo-content.xml',
			'local_import_widget_file'     => WOOSTIFY_SITES_DIR . 'demos/demo-2/widgets.wie',
			'local_import_customizer_file' => WOOSTIFY_SITES_DIR . 'demos/demo-2/customizer.dat',
			'import_preview_image_url'     => WOOSTIFY_SITES_URI . 'demos/demo-2/demo-2.jpg',
			'import_notice'                => __( 'After you import this demo, you will have to setup the slider separately.', 'woostify' ),
			'preview_url'                  => 'https://prodemo.woostify.com/fashion2/',
			'homepage'                     => 'Woostify',
			'blog_page'                    => 'Blog',
			'primary_menu'                 => 'Primary Menu',
			'footer_menu'                  => 'Footer Menu',
			'type'                         => 'pro',
			'page_builder'                 => 'elementor',
		),
		array(
			'id'                           => 2,
			'import_file_name'             => 'Voge - Fashion',
			'local_import_file'            => WOOSTIFY_SITES_DIR . 'demos/demo-3/demo-content.xml',
			'local_import_widget_file'     => WOOSTIFY_SITES_DIR . 'demos/demo-3/widgets.wie',
			'local_import_customizer_file' => WOOSTIFY_SITES_DIR . 'demos/demo-3/customizer.dat',
			'import_preview_image_url'     => WOOSTIFY_SITES_URI . 'demos/demo-3/demo-3.jpg',
			'import_notice'                => __( 'After you import this demo, you will have to setup the slider separately.', 'woostify' ),
			'preview_url'                  => 'https://prodemo.woostify.com/fashion3/',
			'homepage'                     => 'Woostify',
			'blog_page'                    => 'Blog',
			'primary_menu'                 => 'Primary Menu',
			'footer_menu'                  => 'Footer Menu',
			'type'                         => 'pro',
			'page_builder'                 => 'elementor',
		),
		array(
			'id'                           => 3,
			'import_file_name'             => 'Lensvision - sunglasses',
			'local_import_file'            => WOOSTIFY_SITES_DIR . 'demos/demo-4/demo-content.xml',
			'local_import_widget_file'     => WOOSTIFY_SITES_DIR . 'demos/demo-4/widgets.wie',
			'local_import_customizer_file' => WOOSTIFY_SITES_DIR . 'demos/demo-4/customizer.dat',
			'import_preview_image_url'     => WOOSTIFY_SITES_URI . 'demos/demo-4/demo-4.jpg',
			'import_notice'                => __( 'After you import this demo, you will have to setup the slider separately.', 'woostify' ),
			'preview_url'                  => 'https://prodemo.woostify.com/fashion4/',
			'homepage'                     => 'Woostify',
			'blog_page'                    => 'Blog',
			'primary_menu'                 => 'Primary Menu',
			'footer_menu'                  => 'Footer Menu',
			'type'                         => 'pro',
			'page_builder'                 => 'elementor',
		),
		array(
			'id'                           => 4,
			'import_file_name'             => 'Shoebox',
			'local_import_file'            => WOOSTIFY_SITES_DIR . 'demos/demo-5/demo-content.xml',
			'local_import_widget_file'     => WOOSTIFY_SITES_DIR . 'demos/demo-5/widgets.wie',
			'local_import_customizer_file' => WOOSTIFY_SITES_DIR . 'demos/demo-5/customizer.dat',
			'import_preview_image_url'     => WOOSTIFY_SITES_URI . 'demos/demo-5/demo-5.jpg',
			'import_notice'                => __( 'After you import this demo, you will have to setup the slider separately.', 'woostify' ),
			'preview_url'                  => 'https://prodemo.woostify.com/shoebox/',
			'homepage'                     => 'Woostify',
			'blog_page'                    => 'Blog',
			'primary_menu'                 => 'Primary Menu',
			'footer_menu'                  => 'Footer Menu',
			'type'                         => 'pro',
			'page_builder'                 => 'elementor',
		),
		array(
			'id'                           => 5,
			'import_file_name'             => 'Cosmetica - Cosmetic',
			'local_import_file'            => WOOSTIFY_SITES_DIR . 'demos/demo-6/demo-content.xml',
			'local_import_widget_file'     => WOOSTIFY_SITES_DIR . 'demos/demo-6/widgets.wie',
			'local_import_customizer_file' => WOOSTIFY_SITES_DIR . 'demos/demo-6/customizer.dat',
			'import_preview_image_url'     => WOOSTIFY_SITES_URI . 'demos/demo-6/demo-6.png',
			'import_notice'                => __( 'After you import this demo, you will have to setup the slider separately.', 'woostify' ),
			'preview_url'                  => 'https://prodemo.woostify.com/cosmetica/',
			'homepage'                     => 'Woostify',
			'blog_page'                    => 'Blog',
			'primary_menu'                 => 'Primary Menu',
			'footer_menu'                  => 'Footer Menu',
			'type'                         => 'pro',
			'page_builder'                 => 'elementor',
		),
		array(
			'id'                           => 6,
			'import_file_name'             => 'Ankle - Fashion',
			'local_import_file'            => WOOSTIFY_SITES_DIR . 'demos/demo-7/demo-content.xml',
			'local_import_widget_file'     => WOOSTIFY_SITES_DIR . 'demos/demo-7/widgets.wie',
			'local_import_customizer_file' => WOOSTIFY_SITES_DIR . 'demos/demo-7/customizer.dat',
			'import_preview_image_url'     => WOOSTIFY_SITES_URI . 'demos/demo-7/demo-7.png',
			'import_notice'                => __( 'After you import this demo, you should update permalink.', 'woostify' ),
			'preview_url'                  => 'https://prodemo.woostify.com/ankle/',
			'homepage'                     => 'Homepage',
			'blog_page'                    => 'Blog',
			'primary_menu'                 => 'main menu',
			'footer_menu'                  => '',
			'type'                         => 'pro',
			'page_builder'                 => 'elementor',
		),
		array(
			'id'                           => 7,
			'import_file_name'             => 'Pezshop - Pet Care',
			'local_import_file'            => WOOSTIFY_SITES_DIR . 'demos/demo-8/demo-content.xml',
			'local_import_widget_file'     => WOOSTIFY_SITES_DIR . 'demos/demo-8/widgets.wie',
			'local_import_customizer_file' => WOOSTIFY_SITES_DIR . 'demos/demo-8/customizer.dat',
			'import_preview_image_url'     => WOOSTIFY_SITES_URI . 'demos/demo-8/demo-7.png',
			'import_notice'                => __( 'After you import this demo, you should update permalink.', 'woostify' ),
			'preview_url'                  => 'https://prodemo.woostify.com/pezshop/',
			'homepage'                     => 'Woostify',
			'blog_page'                    => 'Blog',
			'primary_menu'                 => 'Primary Menu',
			'footer_menu'                  => 'Footer Menu',
			'type'                         => 'pro',
			'page_builder'                 => 'elementor',
		),
		array(
			'id'                           => 8,
			'import_file_name'             => 'Watch - Watch Shop',
			'local_import_file'            => WOOSTIFY_SITES_DIR . 'demos/demo-9/demo-content.xml',
			'local_import_widget_file'     => WOOSTIFY_SITES_DIR . 'demos/demo-9/widgets.wie',
			'local_import_customizer_file' => WOOSTIFY_SITES_DIR . 'demos/demo-9/customizer.dat',
			'import_preview_image_url'     => WOOSTIFY_SITES_URI . 'demos/demo-9/demo-9.png',
			'import_notice'                => __( 'After you import this demo, you should update permalink.', 'woostify' ),
			'preview_url'                  => 'https://prodemo.woostify.com/watch/',
			'homepage'                     => 'Homepage',
			'blog_page'                    => 'Blog',
			'primary_menu'                 => 'Main Menu',
			'footer_menu'                  => '',
			'type'                         => 'pro',
			'page_builder'                 => 'elementor',
		),
		array(
			'id'                           => 9,
			'import_file_name'             => 'Hippine - Jewelry ',
			'local_import_file'            => WOOSTIFY_SITES_DIR . 'demos/demo-10/demo-content.xml',
			'local_import_widget_file'     => WOOSTIFY_SITES_DIR . 'demos/demo-10/widgets.wie',
			'local_import_customizer_file' => WOOSTIFY_SITES_DIR . 'demos/demo-10/customizer.dat',
			'import_preview_image_url'     => WOOSTIFY_SITES_URI . 'demos/demo-10/demo-10.png',
			'import_notice'                => __( 'After you import this demo, you should update permalink.', 'woostify' ),
			'preview_url'                  => 'https://prodemo.woostify.com/hippine/',
			'homepage'                     => 'Homepage',
			'blog_page'                    => 'Blog',
			'primary_menu'                 => 'main menu',
			'footer_menu'                  => '',
			'type'                         => 'pro',
			'page_builder'                 => 'elementor',
		),
		array(
			'id'                           => 10,
			'import_file_name'             => 'Furnito - Furniture',
			'local_import_file'            => WOOSTIFY_SITES_DIR . 'demos/demo-11/demo-content.xml',
			'local_import_widget_file'     => WOOSTIFY_SITES_DIR . 'demos/demo-11/widgets.wie',
			'local_import_customizer_file' => WOOSTIFY_SITES_DIR . 'demos/demo-11/customizer.dat',
			'import_preview_image_url'     => WOOSTIFY_SITES_URI . 'demos/demo-11/demo-11.png',
			'import_notice'                => __( 'After you import this demo, you should update permalink.', 'woostify' ),
			'preview_url'                  => 'https://prodemo.woostify.com/furnito/',
			'homepage'                     => 'Woostify',
			'blog_page'                    => 'Blog',
			'primary_menu'                 => 'Primary Menu',
			'footer_menu'                  => 'Footer Menu',
			'type'                         => 'pro',
			'page_builder'                 => 'elementor',
		),
		array(
			'id'                           => 11,
			'import_file_name'             => 'Pizza',
			'local_import_file'            => WOOSTIFY_SITES_DIR . 'demos/demo-12/demo-content.xml',
			'local_import_widget_file'     => WOOSTIFY_SITES_DIR . 'demos/demo-12/widgets.wie',
			'local_import_customizer_file' => WOOSTIFY_SITES_DIR . 'demos/demo-12/customizer.dat',
			'import_preview_image_url'     => WOOSTIFY_SITES_URI . 'demos/demo-12/demo-12.png',
			'import_notice'                => __( 'After you import this demo, you should update permalink.', 'woostify' ),
			'preview_url'                  => 'https://prodemo.woostify.com/pizzaria/',
			'homepage'                     => 'Woostify',
			'blog_page'                    => 'Blog',
			'primary_menu'                 => 'Primary Menu',
			'footer_menu'                  => 'Footer Menu',
			'type'                         => 'pro',
			'page_builder'                 => 'elementor',
		),
		array(
			'id'                           => 12,
			'import_file_name'             => 'Urbanstyle',
			'local_import_file'            => WOOSTIFY_SITES_DIR . 'demos/demo-13/demo-content.xml',
			'local_import_widget_file'     => WOOSTIFY_SITES_DIR . 'demos/demo-13/widgets.wie',
			'local_import_customizer_file' => WOOSTIFY_SITES_DIR . 'demos/demo-13/customizer.dat',
			'import_preview_image_url'     => WOOSTIFY_SITES_URI . 'demos/demo-13/demo-13.png',
			'import_notice'                => __( 'After you import this demo, you should update permalink.', 'woostify' ),
			'preview_url'                  => 'https://freedemo.woostify.com/urbanstyle/',
			'homepage'                     => 'Fashion',
			'blog_page'                    => 'Blog',
			'primary_menu'                 => 'Header Primary',
			'footer_menu'                  => 'Footer',
			'type'                         => 'free',
			'page_builder'                 => 'elementor',
		),
		array(
			'id'                           => 13,
			'import_file_name'             => 'Randy',
			'local_import_file'            => WOOSTIFY_SITES_DIR . 'demos/demo-14/demo-content.xml',
			'local_import_widget_file'     => WOOSTIFY_SITES_DIR . 'demos/demo-14/widgets.wie',
			'local_import_customizer_file' => WOOSTIFY_SITES_DIR . 'demos/demo-14/customizer.dat',
			'import_preview_image_url'     => WOOSTIFY_SITES_URI . 'demos/demo-14/demo-14.png',
			'import_notice'                => __( 'After you import this demo, you should update permalink.', 'woostify' ),
			'preview_url'                  => 'https://prodemo.woostify.com/randy/',
			'homepage'                     => 'Woostify',
			'blog_page'                    => 'Blog',
			'primary_menu'                 => 'Primary Menu',
			'footer_menu'                  => 'Footer Menu',
			'type'                         => 'pro',
			'page_builder'                 => 'elementor',
		),
		array(
			'id'                           => 14,
			'import_file_name'             => 'Mega Shop',
			'local_import_file'            => WOOSTIFY_SITES_DIR . 'demos/demo-15/demo-content.xml',
			'local_import_widget_file'     => WOOSTIFY_SITES_DIR . 'demos/demo-15/widgets.wie',
			'local_import_customizer_file' => WOOSTIFY_SITES_DIR . 'demos/demo-15/customizer.dat',
			'import_preview_image_url'     => WOOSTIFY_SITES_URI . 'demos/demo-15/demo-15.png',
			'import_notice'                => __( 'After you import this demo, you should update permalink.', 'woostify' ),
			'preview_url'                  => 'https://prodemo.woostify.com/megashop/',
			'homepage'                     => 'Woostify',
			'blog_page'                    => 'Blog',
			'primary_menu'                 => 'Primary Menu',
			'vertical_menu'                => 'Menu Vertical',
			'footer_menu'                  => 'Footer Menu',
			'type'                         => 'pro',
			'page_builder'                 => 'elementor',
		),
		array(
			'id'                           => 15,
			'import_file_name'             => 'Auto Car',
			'local_import_file'            => WOOSTIFY_SITES_DIR . 'demos/demo-16/data.xml',
			'local_import_widget_file'     => WOOSTIFY_SITES_DIR . 'demos/demo-16/widgets.wie',
			'local_import_customizer_file' => WOOSTIFY_SITES_DIR . 'demos/demo-16/customizer.dat',
			'import_preview_image_url'     => WOOSTIFY_SITES_URI . 'demos/demo-16/demo-16.png',
			'import_notice'                => __( 'After you import this demo, you should update permalink.', 'woostify' ),
			'preview_url'                  => 'https://prodemo.woostify.com/autocar/',
			'homepage'                     => 'Home',
			'blog_page'                    => 'Blog',
			'primary_menu'                 => 'Primary Menu',
			'vertical_menu'                => 'Menu Vertical',
			'type'                         => 'pro',
			'page_builder'                 => 'elementor',
		),
		array(
			'id'                           => 16,
			'import_file_name'             => 'Meins',
			'local_import_file'            => WOOSTIFY_SITES_DIR . 'demos/demo-17/demo-content.xml',
			'local_import_widget_file'     => WOOSTIFY_SITES_DIR . 'demos/demo-17/widgets.wie',
			'local_import_customizer_file' => WOOSTIFY_SITES_DIR . 'demos/demo-17/customizer.dat',
			'import_preview_image_url'     => WOOSTIFY_SITES_URI . 'demos/demo-17/demo-17.png',
			'import_notice'                => __( 'After you import this demo, you should update permalink.', 'woostify' ),
			'preview_url'                  => 'https://prodemo.woostify.com/meins/',
			'homepage'                     => 'Home',
			'blog_page'                    => 'Blog',
			'primary_menu'                 => 'Primary Menu',
			'type'                         => 'pro',
			'page_builder'                 => 'elementor',
		),

	);
}
add_filter( 'woostify_sites_import_files', 'woostify_sites_local_import_files' );



function woostify_register_query_vars( $vars ) {
	$vars[] = 'p';
	return $vars;
}
add_filter( 'query_vars', 'woostify_register_query_vars' );